# Generated by Django 3.2.9 on 2021-11-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='friends',
            field=models.ManyToManyField(related_name='_user_systemuser_friends_+', to='user.SystemUser'),
        ),
    ]
