# Generated by Django 3.2.9 on 2021-11-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_systemuser_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='age',
        ),
    ]
