# Generated by Django 3.2.9 on 2021-11-21 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('tasks', '0003_auto_20211121_1748'),
        ('user', '0003_remove_systemuser_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemUser',
        ),
    ]
